### ISSUE TITLE
Screen: Word Clock

### ISSUE THREAD

**Issue by elParaguayo** [elParaguayo/RPi-InfoScreen-Kivy#22]

**Comment by elParaguayo** [comment]
Starting this one as I wanted a break from the SqueezePlayer one! This should be easier.

I know those words will come back to haunt me...

**Comment by elParaguayo** [comment]
Screenshots:
![screenshot from 2015-10-09 23 29 44](https://cloud.githubusercontent.com/assets/946265/10407085/2796c304-6ede-11e5-808d-90805bf3a379.png)
![screenshot from 2015-10-09 23 30 11](https://cloud.githubusercontent.com/assets/946265/10407086/29764776-6ede-11e5-8b30-a4f382ae5516.png)

**Comment by elParaguayo** [comment]
Need to fix "teno'clock". Can do this by using the "ten" minutes at this point.

**Comment by CraigHissett** [comment]
Love it!

**Comment by elParaguayo** [comment]
Ok - this is done.

Last commit did the following:
- Code tidy-up with comments
- Added ability to add additional language layouts
- Added fade transition between times
