### ISSUE TITLE
Had to add import statements to screen.py in londonbuses and trains

### ISSUE THREAD

**Issue by lleibovici** [elParaguayo/RPi-InfoScreen-Kivy#24]
trains
from kivy.uix.stacklayout import StackLayout
from kivy.uix.scrollview import ScrollView

londonbuses
from kivy.uix.stacklayout import StackLayout

**Comment by elParaguayo** [comment]
Strange. Not raising issues for me but I'm happy to add to the main code. Thanks for reporting.

**Comment by lleibovici** [comment]
Perhaps I have a different version of kivy?

Anyway thanks for the code. It has given me lots of ideas.
Im going to try to write a UPNP controller.

Leo

Sent from Samsung tablet

-------- Original message --------

**Comment by elParaguayo** [comment]
I think you got the bus and trains the wrong way round (the train screen doesn't have a ScrollView widget) but I do agree that the import lines were missing! Will add now.
