### ISSUE TITLE
Screen: Squeezeplayer

### ISSUE THREAD

**Issue by elParaguayo** [elParaguayo/RPi-InfoScreen-Kivy#4]
Not started.

Basic: Allow control/visualisation of squeezeplayers.

**Comment by elParaguayo** [comment]
Screenshots:
![screenshot from 2015-10-04 18 14 40](https://cloud.githubusercontent.com/assets/946265/10269140/7643d70c-6ac5-11e5-91a7-6625ace35d7c.png)
![screenshot from 2015-10-04 18 14 58](https://cloud.githubusercontent.com/assets/946265/10269141/7e06f47e-6ac5-11e5-82a7-3517ecbf4f71.png)

**Comment by CraigHissett** [comment]
Great work!

**Comment by elParaguayo** [comment]
This is a beast of  screen! Things to do before uploading:
- [X] Update playlist if changed
- [x] Select players
- [x] Control volume
- [x] Handle accented characters. Crashing painfully at the moment (fault of pylms module?)
- [x] Handle no players/no server gracefully
- [x] Update image on playlist change
- [x] Tidy up code (my ugliest yet!)

**Comment by CraigHissett** [comment]
Keep going man - amazing work!!

**Comment by elParaguayo** [comment]
I need a break from this for a while. Doing my head in. It's a bit rough around the edges but it works ok. Lots to improve on though.

**Comment by elParaguayo** [comment]
Good enough for release!
