### ISSUE TITLE
Webserver bug

### ISSUE THREAD

**Issue by elParaguayo** [elParaguayo/RPi-InfoScreen-Kivy#64]
Reported on forum: https://www.raspberrypi.org/forums/viewtopic.php?f=41&t=121392&p=932499#p931693

Issue is that screen isn't built before webserver started.

**Comment by DirkUK** [comment]
Unfortunately that doesn't wok. Just before the while loop infoapp is set to the uninstantiated class:

```
infoapp = App.get_running_app()
```

and the while loop is never entered.
If you replace this with

```
infoapp = None
```

it does work as expected.

**Comment by elParaguayo** [comment]
Yes. That would make sense. I'll merge tomorrow.
