### ISSUE TITLE
ADS7846 Touchscreen Y axis reversed?

### ISSUE THREAD

**Issue by jimbolaya** [elParaguayo/RPi-InfoScreen-Kivy#71]
I'm running this on a XPT2046 screen with ADS7846 touchscreen controller.

Since it's an 800x480 screen, the size is fine.

The moving back and forth between screens works fine.

Playing PONG, the paddles are reversed. Sliding the finger up makes the paddle go down and vice versa. Is this a quick setting change somewhere?

**Comment by elParaguayo** [comment]
Not really an issue with this script.

Have you looked at this: https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=58823
