### ISSUE TITLE
[WARNING] Bottle module not found. Cannot start webserver. Error

### ISSUE THREAD

**Issue by harmfulmushroom** [elParaguayo/RPi-InfoScreen-Kivy#76]
I've seen only one thread about this issue, but the suggestions did not help me.  Any idea why this is happening?

**Comment by elParaguayo** [comment]
You have to install bottle separately.

**Comment by harmfulmushroom** [comment]
...Well I am retarded, thanks for clearing that up for me!  I'm too embarrassed to say how long I've spent trying to get this working...

**Comment by elParaguayo** [comment]
Don't worry about it!
