### ISSUE TITLE
ISS HD Stream

### ISSUE THREAD

**Issue by thegnnu** [elParaguayo/RPi-InfoScreen-Kivy#77]
Hi I see you have 1 screen showing the ISS track do you have any idea if you will be doing a HD stream that is now on line and only take one line of bash to give a simple streaming screen.
TerryR

**Comment by elParaguayo** [comment]
I'm not actively working on this code at the moment. However, if you can get it working, I'd happily merge it into the main code.

**Comment by thegnnu** [comment]
I was asking as I do  not have the PI Screen but would get one if I could use it for monitoring the ISS Stream. Do not have any use for the transport screens as long ago retired.

**Comment by elParaguayo** [comment]
Try this branch: https://github.com/elParaguayo/RPi-InfoScreen-Kivy/tree/iss_video

You'll need to enable the screen.

It works on my laptop, but I haven't tested on a pi.
